export const projectsData = [
  {
    id: 1,
    number: "01",
    type: "WEB APP",
    date: "2025",
    name: "College FAQ Chatbot",
    tagline: "RAG-powered AI that answers college queries straight from official documents.",
    description:
      "A Retrieval-Augmented Generation chatbot that lets students ask questions about college handbooks, regulations, fee structures, and academic calendars — with answers grounded in actual institutional documents instead of AI guesswork.",
    bullets: [
      "RAG pipeline with semantic chunking, embeddings, and ChromaDB vector search to ground every answer in uploaded documents",
      "Multi-format document ingestion (PDF, DOCX) with automated parsing, chunking, and indexing pipeline",
      "Local LLM inference via Ollama (Gemma 3 + Nomic Embed Text) — fully self-hosted, no external API costs",
      "Session-based chat with persistent history, source citation tracking, and a feedback rating system",
    ],
    stack: [
      "React",
      "Spring Boot",
      "PostgreSQL",
      "ChromaDB",
      "Ollama",
      "Docker",
      "JPA/Hibernate",
    ],
    gradient: "linear-gradient(135deg, #e91e8c 0%, #c2185b 50%, #880e4f 100%)",
    accentColor: "#e91e8c",
    liveUrl: "#",
    githubUrl: "https://github.com/gufran-09/College-FAQ-Chatbot",
  },
  {
    id: 2,
    number: "02",
    type: "WEB APP",
    date: "2026",
    name: "Agent Ascend",
    tagline: "An AI operating system that routes every prompt to the right model.",
    description:
      "An intelligent multi-agent LLM orchestration platform that classifies incoming prompts and dynamically routes them to the most suitable AI model based on task category, complexity, token cost, and response time — instead of sending everything to a single model.",
    bullets: [
      "Unified routing layer across 4+ LLM providers, eliminating the need for separate provider dashboards",
      "Task decomposition engine that breaks complex prompts into subtasks and assigns each to a specialized agent",
      "Difficulty detection and model recommendation system with pre-execution cost, token, and response-time estimates",
      "Visual dashboard showing prompt flow, task decomposition, model assignment, and execution timeline",
    ],
    stack: [
      "Next.js",
      "Node.js",
      "OpenAI",
      "Gemini",
      "Claude",
      "GPT",
    ],
    gradient: "linear-gradient(135deg, #6366f1 0%, #4338ca 50%, #1e1b4b 100%)",
    accentColor: "#6366f1",
    liveUrl: "#",
    githubUrl: "https://github.com/gufran-09/Agent_Ascend",
  },
  {
    id: 3,
    number: "03",
    type: "WEB APP",
    date: "2026",
    name: "AdaptIQ",
    tagline: "Quizzes that get harder or easier based on how you're actually doing.",
    description:
      "An AI-powered adaptive quiz platform that personalizes question difficulty in real time using ML models trained on user performance data, blending machine learning predictions with rule-based fallbacks for new users.",
    bullets: [
      "Dual-track ML inference — XGBoost (99.95% accuracy) and LightGBM (97.45% accuracy) models predict user level and recommend difficulty, with a rules-based fallback for cold-start users",
      "Adaptive quiz engine with diagnostic, practice, and retest modes, non-repeating question logic, and atomic PostgreSQL locking to prevent race conditions",
      "14-dimensional feature vector blending accuracy, streaks, time patterns, and difficulty breakdown for personalized recommendations",
      "Real-time adaptation with cache invalidation after each quiz, backed by a 78-test suite (38 backend + 40 ML) for reliability",
    ],
    stack: [
      "React",
      "Vite",
      "Express",
      "FastAPI",
      "XGBoost",
      "LightGBM",
      "Supabase",
      "PostgreSQL",
    ],
    gradient: "linear-gradient(135deg, #10b981 0%, #059669 50%, #064e3b 100%)",
    accentColor: "#10b981",
    liveUrl: "https://adapt--iq.vercel.app/",
    githubUrl: "https://github.com/Owais010/Adaptiq",
  },
  {
    id: 4,
    number: "04",
    type: "WEB APP",
    date: "2026",
    name: "Netflix Clone",
    tagline: "A pixel-faithful Netflix UI, rebuilt from scratch with real data.",
    description:
      "A full-stack streaming platform clone replicating Netflix's browsing and playback experience — with Firebase authentication, live movie data from TMDB, and embedded trailer playback, all wrapped in a responsive Netflix-style interface.",
    bullets: [
      "Firebase Authentication for sign up, sign in, and logout, backed by Firestore for user data",
      "Movie discovery powered by the TMDB API across categories like Blockbuster, Only on Netflix, and Top Picks",
      "Dynamic hero banner showcasing featured content with live movie metadata",
      "Embedded YouTube trailer playback with React Router v7 handling page-to-player navigation",
    ],
    stack: [
      "React",
      "Vite",
      "Firebase",
      "React Router",
      "TMDB API",
    ],
    gradient: "linear-gradient(135deg, #e50914 0%, #b20710 50%, #564d4d 100%)",
    accentColor: "#e50914",
    liveUrl: "#",
    githubUrl: "https://github.com/gufran-09/NETFLIX-CLONE",
  }
];

export type Project = (typeof projectsData)[0];
