export type SkillLevel = "Expert" | "Advanced" | "Proficient" | "Familiar";

export type SkillCategory =
  | "Frontend"
  | "Backend"
  | "Database"
  | "DevOps"
  | "Tools";

export type SkillItem = {
  name: string;
  level: SkillLevel;
  years: string;
  projects: string;
  icon: string;
  iconColor: string;
  iconBg: string;
  useCases: string[];
  usedIn: string[];
  docs: string;
};

export const SKILL_CATEGORIES: SkillCategory[] = [
  "Frontend",
  "Backend",
  "Database",
  "DevOps",
  "Tools",
];

export const LEVEL_BADGE_STYLES: Record<
  SkillLevel,
  { background: string; color: string }
> = {
  Expert: { background: "rgba(34,197,94,0.1)", color: "#22c55e" },
  Advanced: { background: "rgba(99,102,241,0.1)", color: "#818cf8" },
  Proficient: { background: "rgba(234,179,8,0.1)", color: "#eab308" },
  Familiar: { background: "rgba(161,161,170,0.1)", color: "#a0a0a0" },
};

export const SKILLS_DATA: Record<SkillCategory, SkillItem[]> = {
  Frontend: [
    {
      name: "React",
      level: "Expert",
      years: "3+",
      projects: "20+",
      icon: "⚛",
      iconColor: "#61DAFB",
      iconBg: "rgba(97,218,251,0.08)",
      useCases: [
        "Component Libraries",
        "SPAs & dashboards",
        "Performance optimization",
        "State management",
      ],
      usedIn: ["DevFlow", "CodeSync", "AuraUI"],
      docs: "https://react.dev",
    },
    {
      name: "TypeScript",
      level: "Expert",
      years: "2+",
      projects: "15+",
      icon: "TS",
      iconColor: "#3178C6",
      iconBg: "rgba(49,120,198,0.1)",
      useCases: ["Type-safe APIs", "Large codebases", "Library authoring"],
      usedIn: ["AuraUI", "DevFlow"],
      docs: "https://www.typescriptlang.org",
    },
    {
      name: "Next.js",
      level: "Advanced",
      years: "2+",
      projects: "10+",
      icon: "N",
      iconColor: "#f0f0f0",
      iconBg: "rgba(255,255,255,0.05)",
      useCases: [
        "SSR & SSG",
        "Full-stack apps",
        "SEO optimization",
        "API routes",
      ],
      usedIn: ["Taskly", "StockSense"],
      docs: "https://nextjs.org",
    },
    {
      name: "Tailwind CSS",
      level: "Expert",
      years: "2+",
      projects: "18+",
      icon: "TW",
      iconColor: "#06B6D4",
      iconBg: "rgba(6,182,212,0.08)",
      useCases: [
        "Rapid UI development",
        "Design systems",
        "Responsive layouts",
      ],
      usedIn: ["DevFlow", "Taskly"],
      docs: "https://tailwindcss.com",
    },
    {
      name: "Framer Motion",
      level: "Advanced",
      years: "1+",
      projects: "8+",
      icon: "FM",
      iconColor: "#6366f1",
      iconBg: "rgba(99,102,241,0.1)",
      useCases: [
        "Page transitions",
        "Micro-interactions",
        "Gesture animations",
      ],
      usedIn: ["Portfolio", "AuraUI"],
      docs: "https://framer.com/motion",
    },
    {
      name: "Redux",
      level: "Advanced",
      years: "2+",
      projects: "7+",
      icon: "RX",
      iconColor: "#764ABC",
      iconBg: "rgba(118,74,188,0.1)",
      useCases: ["Global state", "Complex workflows", "Redux Toolkit"],
      usedIn: ["DevFlow", "CodeSync"],
      docs: "https://redux-toolkit.js.org",
    },
    {
      name: "Vite",
      level: "Proficient",
      years: "1+",
      projects: "10+",
      icon: "VT",
      iconColor: "#646CFF",
      iconBg: "rgba(100,108,255,0.1)",
      useCases: ["Fast dev builds", "Plugin ecosystem", "Library bundling"],
      usedIn: ["AuraUI", "Portfolio"],
      docs: "https://vitejs.dev",
    },
  ],
  Backend: [
    {
      name: "Node.js",
      level: "Expert",
      years: "3+",
      projects: "15+",
      icon: "NO",
      iconColor: "#68A063",
      iconBg: "rgba(104,160,99,0.1)",
      useCases: [
        "REST APIs",
        "Real-time servers",
        "CLI tools",
        "Microservices",
      ],
      usedIn: ["DevFlow", "CodeSync", "StockSense"],
      docs: "https://nodejs.org",
    },
    {
      name: "Python",
      level: "Advanced",
      years: "2+",
      projects: "8+",
      icon: "PY",
      iconColor: "#FFD43B",
      iconBg: "rgba(255,212,59,0.08)",
      useCases: [
        "FastAPI backends",
        "Data processing",
        "Automation scripts",
        "ML pipelines",
      ],
      usedIn: ["StockSense", "ByteNotes"],
      docs: "https://python.org",
    },
    {
      name: "Express.js",
      level: "Expert",
      years: "3+",
      projects: "12+",
      icon: "EX",
      iconColor: "#f0f0f0",
      iconBg: "rgba(255,255,255,0.05)",
      useCases: [
        "REST API design",
        "Middleware",
        "Auth systems",
        "Rate limiting",
      ],
      usedIn: ["DevFlow", "StockSense"],
      docs: "https://expressjs.com",
    },
    {
      name: "GraphQL",
      level: "Proficient",
      years: "1+",
      projects: "4+",
      icon: "GQ",
      iconColor: "#E10098",
      iconBg: "rgba(225,0,152,0.08)",
      useCases: ["Flexible APIs", "Real-time subscriptions", "Schema design"],
      usedIn: ["DevFlow"],
      docs: "https://graphql.org",
    },
  ],
  Database: [
    {
      name: "PostgreSQL",
      level: "Advanced",
      years: "2+",
      projects: "10+",
      icon: "PG",
      iconColor: "#336791",
      iconBg: "rgba(51,103,145,0.1)",
      useCases: [
        "Complex queries",
        "Migrations",
        "Performance tuning",
        "Full-text search",
      ],
      usedIn: ["DevFlow", "StockSense"],
      docs: "https://postgresql.org",
    },
    {
      name: "MongoDB",
      level: "Advanced",
      years: "2+",
      projects: "7+",
      icon: "MG",
      iconColor: "#4DB33D",
      iconBg: "rgba(77,179,61,0.1)",
      useCases: ["Document storage", "Aggregation pipelines", "Atlas search"],
      usedIn: ["CodeSync", "ByteNotes"],
      docs: "https://mongodb.com",
    },
    {
      name: "Redis",
      level: "Proficient",
      years: "1+",
      projects: "5+",
      icon: "RD",
      iconColor: "#DC3E3E",
      iconBg: "rgba(220,62,62,0.08)",
      useCases: ["Caching", "Session storage", "Rate limiting", "Pub/Sub"],
      usedIn: ["CodeSync", "DevFlow"],
      docs: "https://redis.io",
    },
    {
      name: "Prisma",
      level: "Advanced",
      years: "1+",
      projects: "6+",
      icon: "PR",
      iconColor: "#5A67D8",
      iconBg: "rgba(90,103,216,0.1)",
      useCases: ["Type-safe ORM", "Database migrations", "Schema design"],
      usedIn: ["Taskly", "DevFlow"],
      docs: "https://prisma.io",
    },
  ],
  DevOps: [
    {
      name: "Docker",
      level: "Advanced",
      years: "2+",
      projects: "8+",
      icon: "DO",
      iconColor: "#0DB7ED",
      iconBg: "rgba(13,183,237,0.08)",
      useCases: [
        "Containerization",
        "Docker Compose",
        "Multi-stage builds",
        "Local dev parity",
      ],
      usedIn: ["DevFlow", "StockSense"],
      docs: "https://docs.docker.com",
    },
    {
      name: "AWS",
      level: "Proficient",
      years: "1+",
      projects: "5+",
      icon: "AW",
      iconColor: "#FF9900",
      iconBg: "rgba(255,153,0,0.08)",
      useCases: [
        "EC2 & S3",
        "Lambda functions",
        "CloudFront CDN",
        "RDS databases",
      ],
      usedIn: ["StockSense", "DevFlow"],
      docs: "https://aws.amazon.com/docs",
    },
    {
      name: "CI/CD",
      level: "Proficient",
      years: "2+",
      projects: "6+",
      icon: "CI",
      iconColor: "#f0f0f0",
      iconBg: "rgba(255,255,255,0.05)",
      useCases: [
        "GitHub Actions",
        "Automated testing",
        "Auto deployment",
        "Quality gates",
      ],
      usedIn: ["AuraUI", "DevFlow"],
      docs: "https://docs.github.com/actions",
    },
  ],
  Tools: [
    {
      name: "Git",
      level: "Expert",
      years: "3+",
      projects: "50+",
      icon: "GT",
      iconColor: "#F05133",
      iconBg: "rgba(240,81,51,0.08)",
      useCases: [
        "Version control",
        "Git flow",
        "Code review",
        "Open source contrib",
      ],
      usedIn: ["All projects"],
      docs: "https://git-scm.com/doc",
    },
    {
      name: "Figma",
      level: "Proficient",
      years: "2+",
      projects: "10+",
      icon: "FG",
      iconColor: "#F24E1E",
      iconBg: "rgba(242,78,30,0.08)",
      useCases: [
        "UI design",
        "Prototyping",
        "Design handoff",
        "Component design",
      ],
      usedIn: ["AuraUI", "Portfolio"],
      docs: "https://figma.com",
    },
    {
      name: "Postman",
      level: "Expert",
      years: "3+",
      projects: "15+",
      icon: "PM",
      iconColor: "#FF6C37",
      iconBg: "rgba(255,108,55,0.08)",
      useCases: [
        "API testing",
        "Collection docs",
        "Mock servers",
        "Automation",
      ],
      usedIn: ["DevFlow", "StockSense"],
      docs: "https://learning.postman.com",
    },
    {
      name: "VS Code",
      level: "Expert",
      years: "3+",
      projects: "50+",
      icon: "VS",
      iconColor: "#007ACC",
      iconBg: "rgba(0,122,204,0.1)",
      useCases: ["Primary editor", "Extension dev", "Remote SSH", "Debugging"],
      usedIn: ["All projects"],
      docs: "https://code.visualstudio.com/docs",
    },
  ],
};

export const CURRENTLY_LEARNING = [
  "Rust",
  "WebAssembly",
  "Three.js",
  "LangChain",
  "Kubernetes",
  "Bun.js",
  "Solid.js",
  "tRPC",
  "Tauri",
  "Zig",
];

export const PROJECT_FOCUS_ALIASES: Record<string, string> = {
  DevFlow: "Flyout Tours",
  CodeSync: "Whirlpool",
  AuraUI: "Agent Ascend",
  Taskly: "Event Manager",
  Portfolio: "Agent Ascend",
  "All projects": "Flyout Tours",
};
